name: Deploy static content to Pages

on:
  push:
    branches: 
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare public directory
        run: |
          mkdir -p public
          cp -r css img js index.html public/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages  # Gałąź docelowa dla deployu
          folder: public  # Folder, który ma być zdeployowany
